import type { Metadata } from "next";
import { Geist_Mono, Inria_Serif } from "next/font/google";
import "./globals.css";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inriaSerif = Inria_Serif({
  subsets: ["latin"],
  weight:["400","700"]

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inriaSerif.className} ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
